
// Objective-C API for talking to the following Go packages
//
//	github.com/ftauth/sdk-mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __FTAuthInternal_FRAMEWORK_H__
#define __FTAuthInternal_FRAMEWORK_H__

#include "Ftauthinternal.objc.h"
#include "Universe.objc.h"

#endif
